using UnityEngine;
using Combating.Scripts;

namespace Crafting.Scripts
{
    /// <summary>
    /// Specialized script to handle fuel jerrycan visuals and logic.
    /// Implements IItemFunctional, IItemUseAction, and IItemPickupAction to restore fuel to the entity's tank.
    /// </summary>
    [ExecuteAlways]
    public class FuelController : MonoBehaviour, IItemFunctional, IItemUseAction, IItemPickupAction
    {
        // Economy Reliability Constants
        private const float FUEL_AMOUNT = 40f;

        [Header("Visuals Configuration")]
        public bool generateDefaultVisuals = false;
        public float orbScale = 0.6f;
        public Color fuelColor = new Color(0f, 0.8f, 1f); // Cyan-ish blue

        void Awake()
        {
            if (generateDefaultVisuals) GenerateJerrycanVisuals();
        }

        public void OnUseItem(GameObject entity) => ApplyEffect(entity);
        public void OnPickupItem(GameObject entity) => ApplyEffect(entity);

        public void ApplyEffect(GameObject entity)
        {
            var propulsion = entity.GetComponent<PropulsionController>() ??
                             entity.GetComponentInParent<PropulsionController>() ??
                             entity.GetComponentInChildren<PropulsionController>();

            if (propulsion != null)
            {
                propulsion.AddFuel(50f);
                Debug.Log($"<color=cyan>[FuelItem]</color> Combustible restaurado en {entity.name}.");
            }
            else
            {
                Debug.LogWarning("[FuelItem] No se encontró PropulsionController para recargar combustible.");
            }
        }

        public void GenerateJerrycanVisuals()
        {
            // Remove previous autogenerated visuals
            foreach (Transform child in transform)
            {
                if (child.name.StartsWith("Xenobot_Fuel_"))
                {
                    if (Application.isPlaying) Destroy(child.gameObject);
                    else DestroyImmediate(child.gameObject);
                }
            }

            // Create a stylized jerrycan using primitives
            GameObject body = GameObject.CreatePrimitive(PrimitiveType.Cube);
            body.name = "Xenobot_Fuel_Body";
            body.transform.SetParent(transform, false);
            body.transform.localScale = new Vector3(orbScale, orbScale * 1.2f, orbScale * 0.5f);
            DestroyPrimacyColliders(body);

            GameObject neck = GameObject.CreatePrimitive(PrimitiveType.Cylinder);
            neck.name = "Xenobot_Fuel_Neck";
            neck.transform.SetParent(body.transform, false);
            neck.transform.localPosition = new Vector3(0.3f, 0.5f, 0);
            neck.transform.localScale = new Vector3(0.4f, 0.2f, 0.4f);
            DestroyPrimacyColliders(neck);

            // Apply Material
            var shader = Shader.Find("Universal Render Pipeline/Unlit") ?? Shader.Find("Unlit/Color");
            var mat = new Material(shader);
            mat.color = fuelColor;

            body.GetComponent<MeshRenderer>().sharedMaterial = mat;
            neck.GetComponent<MeshRenderer>().sharedMaterial = mat;
        }

        private void DestroyPrimacyColliders(GameObject go)
        {
            if (go.TryGetComponent<Collider>(out var c))
            {
                if (Application.isPlaying) Destroy(c);
                else DestroyImmediate(c, true);
            }
        }
    }
}
