using UnityEngine;
using UnityEngine.EventSystems;
#if ENABLE_INPUT_SYSTEM
using UnityEngine.InputSystem.UI;
#endif

namespace NGO.UI
{
    /// <summary>
    /// Asegura que cada escena tenga un EventSystem funcional y evita duplicados
    /// durante las transiciones de red.
    /// </summary>
    public class EventSystemFixer : MonoBehaviour
    {
        private void Awake()
        {
            // Buscar todos los EventSystems en la escena
            EventSystem[] systems = FindObjectsByType<EventSystem>(FindObjectsSortMode.None);

            if (systems.Length > 1)
            {
                // Si hay más de uno, nos quedamos con el primero y destruimos los demás
                for (int i = 1; i < systems.Length; i++)
                {
                    Destroy(systems[i].gameObject);
                }
                Debug.Log("[UI Fixer] EventSystem duplicado eliminado.");
            }
            else if (systems.Length == 0)
            {
                // Si no hay ninguno, creamos uno básico
                GameObject eventSystem = new GameObject("EventSystem_AutoGenerated");
                eventSystem.AddComponent<EventSystem>();

                #if ENABLE_INPUT_SYSTEM
                eventSystem.AddComponent<InputSystemUIInputModule>();
                #else
                eventSystem.AddComponent<StandaloneInputModule>();
                #endif

                Debug.Log("[UI Fixer] No se encontró EventSystem. Se ha creado uno automáticamente.");
            }

            // Opcional: Asegurarse de que el módulo de entrada sea el correcto
            ConfigureInputModule(systems.Length > 0 ? systems[0] : null);
        }

        private void ConfigureInputModule(EventSystem es)
        {
            if (es == null) return;

#if ENABLE_INPUT_SYSTEM
            if (es.GetComponent<InputSystemUIInputModule>() == null)
            {
                // Eliminar el módulo antiguo si existe
                StandaloneInputModule oldModule = es.GetComponent<StandaloneInputModule>();
                if (oldModule != null) DestroyImmediate(oldModule);

                es.gameObject.AddComponent<InputSystemUIInputModule>();
            }
#else
            if (es.GetComponent<StandaloneInputModule>() == null)
            {
                es.gameObject.AddComponent<StandaloneInputModule>();
            }
#endif
        }
    }
}
